import './Terms.css';

import { NavLink } from 'react-router-dom';

export default function Terms() {

    return (
        <div>
            <div className="custom-container">
                <div className="text terms">
                    <h1>World Wiser Sport Committee (WWSC) Website Terms and Conditions of Use</h1>
                    <h2>INTRODUCTION</h2>
                    <p>Welcome to visit our web site at <NavLink to="/">https://worldwisersport.org/</NavLink> (the “Site”). This Site is owned by the World Wiser Sport Committee (the “WWSC”). By visiting our website, you are deemed to have read, understood, and agreed to accept and adhere to the following terms and conditions as stated in this agreement (hereafter referred to as “User Agreement”), along with our <NavLink to="/wwsc-privacy-policy">Privacy Policy</NavLink> (please refer to the Privacy Policy section below for more information).</p>
                    <p>This agreement is in effect as of <strong>November 12, 2014.</strong></p>
                    <p>The following terminology applies to these Terms and Conditions, Privacy Policy and Disclaimer Notice and any or all agreements: “Users”, “You” and “Your” refer to you, the person accessing this website and accepting the website’s terms and conditions. “The WWSC”, “Ourselves”, “We” and “Us”, refer to the World Wiser Sport Committee. “Party”, “Parties”, or “Us”, refer to both the Users and ourselves, or either the Users or ourselves. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>
                    <h2>OWNERSHIP OF THE SITE AND ITS CONTENTS</h2>
                    <p>This Site is owned by the WWSC. Unless otherwise indicated, all of the content featured or displayed on this Site, including, but not limited to text, graphics, data, photographic images, videos, sound, illustrations, and the selection and arrangement thereof (“WWSC Content”), is owned by the WWSC, and all rights are reserved.</p>
                    <h2>TRADEMARKS/COPYRIGHTS</h2>
                    <p>WWSC Trademarks, Service Marks, the WWSC logo, and any other WWSC word marks, design, name or slogan contained in the Site are the intellectual property of the WWSC, and may not be copied, imitated or used, in whole or in part, without prior written permission of the WWSC. All content and materials belonging to the WWSC (“WWSC Content”) available on the Site, including but not limited to text, graphics, website name, images and logos are the intellectual property of the WWSC, and are protected by applicable copyright and trademark laws in the United States and other countries. Any unauthorized use, including but not limited to the reproduction, distribution, display or transmission of any WWSC Content on this Site is strictly prohibited, unless specifically authorized by the WWSC in writing.</p>
                    <p>Other third party trademarks, registered trademarks, and organization/company names and/or their logos (“third party IP”) mentioned in the Site are the intellectual property of the corresponding third party. Any unauthorized used of the third party IP should be prohibited, unless specifically authorized by the corresponding third party. The WWSC will not be liable or responsible for the unauthorized use of the third party IP by Users of the Site.</p>
                    <h2>RESPONSIBLE USE AND CONDUCT</h2>
                    <p>By visiting our website and accessing the information, resources, services, registration, training and applications we provide for you, either directly or indirectly (hereafter referred to as “Resources”), you agree to use these Resources only for the purposes intended as permitted by (a) the terms of this User Agreement, and (b) applicable laws, regulations and generally accepted online practices or guidelines.</p>
                    <p>Wherein, you understand that:</p>
                    <ol type="a">
                        <li>In order to access our Resources, you may be required to provide certain information about yourself (such as identification, contact information, etc.) as part of the registration process, or as part of your ability to use the Resources. You agree that any information you provide will always be accurate, correct, and up to date.</li>
                        <li>You are responsible for maintaining the confidentiality of any login information associated with any account you use to access our Resources. Accordingly, you are responsible for all activities that occur under your account(s).</li>
                        <li>Accessing (or attempting to access) any of our Resources by any means other than through the means we provide is strictly prohibited. You specifically agree not to access (or attempt to access) any of our Resources through any automated, unethical or unconventional means.</li>
                        <li>Engaging in any activity that disrupts or interferes with our Resources, including the servers and/or networks at which our Resources are located or to which our Resources are connected, is strictly prohibited.</li>
                        <li>Attempting to copy, duplicate, reproduce, sell, trade, or resell our Resources is strictly prohibited.</li>
                        <li>You are solely responsible for any consequences, losses, or damages that we may directly or indirectly incur or suffer due to any unauthorized activities conducted by you, as illustrated above, and you may incur criminal or civil liability.</li>
                        <li>We do not assume any liability for any content posted by you or any other third party users of our website. However, any content posted by you using any open communication tools on our website, provided that it does not violate or infringe on any third party intellectual property rights, becomes the property of the WWSC, and as such, gives us a perpetual, irrevocable, worldwide, royalty-free, exclusive license to reproduce, modify, adapt, translate, publish, publicly display and/or distribute as we see fit. This only refers and applies to content posted via open communication tools as described, and does not refer to information that is provided as part of the registration process necessary in order to use our Resources. All information provided as part of our registration process is covered by our Privacy Policy.</li>
                        <li>You agree to indemnify and hold harmless the WWSC, and their directors, officers, managers, employees, volunteers, donors, and agents from and against all losses, expenses, damages and costs, including reasonable attorneys’ fees, resulting from any violation of this User Agreement or the failure to fulfill any obligations relating to your account incurred by you or any other person using your account. We reserve the right to take over the exclusive defense of any claim for which we are entitled to indemnification under this User Agreement. In such event, you shall provide us with such cooperation as is reasonably requested by us.</li>
                    </ol>
                    <h2>PRIVACY POLICY</h2>
                    <p>Your privacy is very important to us, which is why we have created a separate Privacy Policy in order to explain in detail how we collect, manage, process, secure, and store your private information. Our privacy policy is included under the scope of this User Agreement. To read our privacy policy in its entirety, click <NavLink to="/wwsc-privacy-policy">here</NavLink>.</p>
                    <h2>LINKS</h2>
                    <p>You may not create a link to any page of this Site without our prior written consent. If you do create a link to a page of this Site, you do so at your own risk and the limitations set out below will apply to your use of this Site by linking to it.</p>
                    <p>We do not monitor or review the content of other party’s websites which are linked from this Site. Opinions expressed or materials appearing on such websites are not necessarily shared or endorsed by us, and we should not be regarded as the publisher of such opinions or material. Please be aware that we are not responsible for the privacy practices, or content, of these sites. We encourage our users to be aware of the privacy statements of these sites. You should evaluate the security and trustworthiness of any other site connected to this site or accessed through this site by yourself, before disclosing any personal information to them. The WWSC will not be responsible for any loss or damage in whatever manner, howsoever caused, resulting from your disclosure to third parties of personal information.</p>
                    <h2>DISCLAIMER NOTICE</h2>
                    <h3>LIMITATION OF WARRANTIES</h3>
                    <p>By using our website, you understand and agree that all Resources we provide are “as is” and “as available”. This means that we do not represent or warrant to you that:</p>
                    <ol type='i'>
                        <li>the use of our Resources will meet your needs or requirements.</li>
                        <li>the use of our Resources will be uninterrupted, timely, secure or free from errors.</li>
                        <li>the information obtained by using our Resources will be accurate or reliable, and</li>
                        <li>any defects in the operation or functionality of any Resources we provide will be repaired or corrected.</li>
                    </ol>
                    <p>Furthermore, you understand and agree that:</p>
                    <ol type='i'>
                        <li>any content downloaded or otherwise obtained through the use of our Resources is done at your own discretion and risk, and that you are solely responsible for any damage to your computer or other devices for any loss of data that may result from the download of such content, and</li>
                        <li>no information or advice, whether expressed, implied, oral or written, obtained by you from the WWSC or through any Resources we provide shall create any warranty, guarantee, or conditions of any kind, except for those expressly outlined in this User Agreement.</li>
                    </ol>
                    <h3>LIMITATION OF LIABILITY</h3>
                    <p>The WWSC will not be liable for any direct, indirect, incidental, consequential or exemplary loss or damages which may be incurred by you as a result of using our Resources, or as a result of any changes, data loss or corruption, cancellation, loss of access, or downtime to the full extent that applicable limitation of liability laws apply.</p>
                    <h3>LANGUAGE TRANSLATION DISCLAIMER</h3>
                    <p>The information contained in this Site may be translated to other languages for the convenience of users of this Site (the “translations”). The Site is being translated through “human translation” and “machine translation” dynamically through Google Translate. Because Google Translate is an external website, the WWSC does not have control of the quality or accuracy of translated content. All WWSC website content that is filtered through Google Translate may result in unexpected and unpredictable degradation of portions of text, images and the general appearance on translated pages. Google Translate may maintain unique privacy and use policies. These policies are not controlled by the WWSC and are not associated with the WWSC privacy and use policies.</p>
                    <p>The official text is written in English and the English version of the Site is the only version endorsed by the WWSC. If any questions arise related to the accuracy of the information contained in the translations, please refer to the official English version. Where there is any question, the English version is always the authoritative version of the website.</p>
                    <p>Some items on the Site may not be translated, such as images containing text, documents, maps, and web page elements. In addition, some features on the site may not work in the translated versions. If you have any questions about information that appears on our site, please <NavLink to="/contact-us">contact us</NavLink>.</p>
                    <h3>FORCE MAJEURE</h3>
                    <p>Neither party shall be liable to the other for any failure to perform any obligation under any agreement which is due to an event beyond the control of such party, including but not limited to any uncontrollable natural forces , terrorism, war, political insurgence, insurrection, riot, civil unrest, act of civil or military authority, uprising, earthquake, flood or any other natural or man made eventuality outside of our control, which causes the termination of an agreement or contract entered into, nor which could have been reasonably foreseen. Any party affected by such event shall forthwith inform the other party of the same and shall use all reasonable endeavours to comply with the terms and conditions of any agreement contained herein.</p>
                    <h3>WAIVER</h3>
                    <p>Failure of either party to insist upon strict performance of any provision of this or any agreement or the failure of either party to exercise any right or remedy to which it, he or they are entitled hereunder shall not constitute a waiver thereof and shall not cause a diminution of the obligations under this or any agreement. No waiver of any of the provisions of this or any agreement shall be effective unless it is expressly stated to be such and signed by both parties.</p>
                    <h2>TERMINATION OF USE</h2>
                    <p>You agree that we may, at our sole discretion, suspend or terminate your access to all or part of our website and Resources with or without notice and for any reason, including, without limitation, breach of this User Agreement. Any suspected illegal, fraudulent or abusive activity may be grounds for terminating your relationship with us and may be referred to appropriate law enforcement authorities. Upon suspension or termination, your right to use the Resources we provide will immediately cease, and we reserve the right to remove or delete any information that you may have on file with us, including any account or login information.</p>
                    <h2>GOVERNING LAW</h2>
                    <p>This website is controlled by the WWSC from our office located in the state of California, USA. The laws of the state of California govern these terms and conditions. By accessing this Site you consent to these terms and conditions and to the exclusive jurisdiction of the California courts in all disputes arising out of such access. If any of these terms are deemed invalid or unenforceable for any reason (including, but not limited to the exclusions and limitations set out above), then the invalid or unenforceable provision will be severed from these terms and the remaining terms will continue to apply. Failure of the WWSC to enforce any of the provisions set out in these Terms and Conditions and any agreement, or failure to exercise any option to terminate, shall not be construed as waiver of such provisions and shall not affect the validity of these Terms and Conditions or of any agreement or any part thereof, or the right thereafter to enforce each and every provision. These Terms and Conditions shall not be amended, modified, varied or supplemented except in writing and signed by duly authorized representatives of the WWSC.</p>
                    <h2>NOTIFICATION OF CHANGES</h2>
                    <p>The WWSC reserves the right to change any of the terms and conditions contained in this User Agreement, or any policy or guideline of the Site, at any time and in its sole discretion. When we make changes, we will revise the “last updated” date at the top of the User Agreement. Any changes will be effective immediately upon posting on the Site. Your continued use of the Site following the posting of changes will constitute your acceptance of such changes. We encourage you to review the User Agreement whenever you visit our website.</p>
                    <h2>CONTACT INFORMATION</h2>
                    <p>Our contact information can be found on our <NavLink to="/contact-us">Contact Us</NavLink> link on our website.</p>
                    <p>If you have any questions or comments about our website Terms and Condition of Use as outlined above, you can contact us at:</p>
                    <div className="address">
                        <p><strong>World Wiser Sport Committee</strong></p>
                        <p>709 E. Colorado Boulevard, Suite 270,</p>
                        <p>Pasadena, CA 91101, USA</p>
                        <p>Email: <a href="info@worldwisersport.org"><i>info@worldwisersport.org</i></a></p>
                        <p>Tel: (626) 795-7485</p>
                    </div>
                    <p>© Copyright 2014-2023. All rights reserved by the World Wiser Sport Committee.</p>
                </div>
            </div>
        </div>
    )
}
